apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kilo-server-ingress
  namespace: kilo-guardian
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: server.kilo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kilo-frontend
            port:
              number: 80
